language: 
    - python

services:
    - postgresql

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: osx
      osx_image: xcode8
      sudo: false
      language: generic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/llvm-mirror/clang.git ~/llvm; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod a+x ~/llvm/tools/scan-build-py/bin/intercept-build; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=~/llvm/tools/scan-build-py/bin:$PATH; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYTHONPATH=~/llvm/tools/scan-build-py/; fi 
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update;               fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/versions/thrift090;                fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen;               fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz -O; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xf clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz -C ~/; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=~/clang+llvm-3.8.0-x86_64-apple-darwin/bin/:$PATH; fi

install:
    - pip install -r ./.ci/python_requirements
    - pip install nose pep8
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PG_DATA=$(brew --prefix)/var/postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}; cat postgres.log; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cat postgres.log; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then psql -c 'create database travis_ci_test;' -U postgres; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cat postgres.log; fi


addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise
        packages:
            - doxygen
            - libpq-dev
            - clang-3.8
            - clang-tidy-3.8
            - libc6-dev-i386
            - gcc-multilib
            - thrift-compiler

    postgresql: "9.3"

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make travis; fi
    - make test
