.TH CODECHECKER 1
.SH NAME
CodeChecker \- static analysis infrastructure built upon the LLVM/Clang
toolchain
.SH SYNOPSIS
.B CodeChecker
.RI --help
.SH DESCRIPTION
.B CodeChecker
is a static analysis infrastructure built upon the LLVM/Clang
toolchain. CodeChecker gives developers an invocation to analyse their
projects and shows the results in a lightweight web application.
.br
To see a list of all available commands, as this manpage is not yet fully done,
please execute \fBCodeChecker --help\fP. Each sub-command is given its own
documentation.
.br
.SH AUTHOR
CodeChecker is developed by the CodeChecker team at Ericsson.
.SH BUG REPORTS
Please file bug reports on GitHub: \fIhttp://github.com/Ericsson/codechecker\fP
